import { createContext, useContext, useState, useCallback } from 'react';

const translations = {
  en: {
    appName: 'Drummate',
    practice: 'Practice',
    report: 'Report',
    metronome: 'Metronome',
    addItem: 'Add Practice Item',
    duplicateItem: 'A practice item with this name already exists.',
    enterName: 'Enter practice item name',
    newItemPlaceholder: 'New practice item...',
    add: 'Add',
    cancel: 'Cancel',
    edit: 'Edit',
    done: 'Done',
    archive: 'Archive',
    unarchive: 'Unarchive',
    showArchived: 'Show Archived',
    hideArchived: 'Hide Archived',
    showTrash: 'Show Trash',
    hideTrash: 'Hide Trash',
    restore: 'Restore',
    permanentDelete: 'Delete Permanently',
    confirmPermanentDelete: 'This will permanently delete this item and all its practice logs. This cannot be undone. Continue?',
    daysLeft: '{days}d left',
    delete: 'Delete',
    merge: 'Merge',
    mergePickerTitle: 'Merge into…',
    mergeSearchPlaceholder: 'Search items',
    mergeArchivedTag: '(archived)',
    mergeEmptyState: 'No other items to merge into.',
    mergeConfirmTitle: 'Confirm merge',
    mergeConfirmBody: 'Merge "{source}" into "{target}"? All practice history from "{source}" will be attributed to "{target}". "{source}" will be deleted.',
    mergeConfirmAction: 'Merge',
    mergeNoOtherItems: 'No other items',
    start: 'Start',
    stop: 'Stop',
    today: 'Today',
    yesterday: 'Yesterday',
    totalPracticeTime: 'Total Practice Time',
    minutes: 'minutes',
    hours: 'hours',
    timeUnit: 'Time Unit',
    noPracticeRecorded: 'No practice recorded',
    noPracticeItems: 'No practice items configured. Go to Practice to add some!',
    selectCategory: 'Select category',
    noFundamentalsYet: 'No fundamentals yet',
    noSongsYet: 'No songs yet',
    addFirstItem: 'Add your first practice item',
    generateReport: 'Generate Report',
    dailyReport: 'Daily Report',
    copyToClipboard: 'Copy to Clipboard',
    copied: 'Copied!',
    close: 'Close',
    editTime: 'Edit Time',
    addTime: 'Add Time',
    addManualTime: 'Add Practice Time',
    durationMinutes: 'Duration (minutes)',
    save: 'Save',
    deleteTime: 'Remove All Time',
    confirmDeleteTime: 'Remove all practice time for this item on this day?',
    selectItem: 'Select Item',
    noItemsToAdd: 'All items already have logs for this day',
    archived: 'Archived',
    categories: {
      fundamentals: 'Fundamentals',
      songs: 'Songs',
      archived: 'Archived',
      fundamentalsShort: 'F',
      songsShort: 'S',
    },
    date: 'Date',
    total: 'Total',
    tapTempo: 'Tap Tempo',
    accentBeat1: 'Accent Beat 1',
    bpm: 'BPM',
    sequencer: 'Complex Rhythm',
    sequencerEditSlot: 'Editing Slot',
    sequencerTapToAdd: 'Tap to add',
    sequencerEmpty: 'Tap a subdivision below to start building your rhythm',
    sequencerInsertBefore: 'Before',
    sequencerInsertAfter: 'After',
    rest: 'Rest',
    soundTypes: {
      click: 'Click',
      woodBlock: 'Wood',
      hiHat: 'Hi-Hat',
      rimshot: 'Rimshot',
      beep: 'Beep',
    },
    tempoNames: {
      grave: 'Grave',
      largo: 'Largo',
      larghetto: 'Larghetto',
      adagio: 'Adagio',
      andante: 'Andante',
      moderato: 'Moderato',
      allegro: 'Allegro',
      vivace: 'Vivace',
      presto: 'Presto',
      prestissimo: 'Prestissimo',
    },
    auth: {
      signIn: 'Sign In',
      signUp: 'Sign Up',
      signOut: 'Sign Out',
      email: 'Email',
      password: 'Password',
      name: 'Display Name',
      noAccount: "Don't have an account?",
      hasAccount: 'Already have an account?',
      syncing: 'Syncing...',
      sessionExpired: 'Session expired. Please sign in again.',
    },
    settings: 'Settings',
    language: 'Language',
    handsFree: {
      title: 'Hands-Free Mode',
      description: 'Say "Drummate" to activate',
      detected: 'Listening...',
      listening: 'Listening for command...',
      commandError: "Didn't understand that command",
      commandConfirm: 'Command received',
      micPermission: 'Microphone permission required',
      loading: 'Loading voice models...',
      error: 'Voice detection error',
      unsupportedBrowser: 'Hands-free mode is only supported in Chrome.',
    },
    reportSubpages: {
      daily: 'Daily',
      weekly: 'Weekly',
      monthly: 'Monthly',
      yearly: 'Yearly',
      stats: 'Stats',
    },
    stats: {
      overview: 'Overview',
      streaks: 'Streaks',
      records: 'Records',
      totalPracticeTime: 'Total Practice Time',
      totalPracticeDays: 'Total Practice Days',
      totalSessions: 'Total Sessions',
      avgDailyTime: 'Avg. Daily Practice',
      currentStreak: 'Current Streak',
      longestStreak: 'Longest Streak',
      longestDayTime: 'Best Single Day',
      mostPracticedItem: 'Most Practiced Item',
      bestMonth: 'Best Month',
      days: 'days',
    },
    analytics: {
      totalThisWeek: 'Total This Week',
      totalThisMonth: 'Total This Month',
      totalThisYear: 'Total This Year',
      weekOf: 'Week of',
      noDataThisWeek: 'No practice this week',
      noDataThisMonth: 'No practice this month',
      noDataThisYear: 'No practice this year',
      weeklyTrend: 'Weekly Trend',
      monthlyTrend: 'Monthly Trend',
      practiceDays: 'Practice Days',
      weekdays: {
        mon: 'Mon',
        tue: 'Tue',
        wed: 'Wed',
        thu: 'Thu',
        fri: 'Fri',
        sat: 'Sat',
        sun: 'Sun',
      },
      months: {
        jan: 'Jan', feb: 'Feb', mar: 'Mar', apr: 'Apr',
        may: 'May', jun: 'Jun', jul: 'Jul', aug: 'Aug',
        sep: 'Sep', oct: 'Oct', nov: 'Nov', dec: 'Dec',
      },
    },
    naturalVoice: {
      title: 'Natural Voice (AI)',
      description: 'Use AI-powered natural voice instead of system voice',
      size: 'One-time download: ~86 MB',
      downloading: 'Downloading voice model...',
      ready: 'Ready',
      error: 'Failed to load voice model',
      requires: 'Enable AI Coach or Hands-Free Mode first',
      unsupportedLang: 'Not available in Chinese',
    },
    aiCoach: {
      title: 'AI Coach',
      description: 'Get personalized encouragement based on your practice data',
    },
    llmCoach: {
      buttonLabel: 'AI Coach',
      modalTitle: 'Drummate says...',
      downloadTitle: 'Meet Your AI Coach',
      downloadBody: 'Generate personalized encouragement based on your practice data using an on-device AI model.',
      downloadSize: 'One-time download: ~350 MB',
      downloadPrivacy: 'Everything runs on your device. No data leaves your browser.',
      downloadButton: 'Download AI Model',
      downloadOnce: 'This only happens once',
      downloading: 'Downloading AI model...',
      loading: 'Loading AI model...',
      generating: 'Thinking...',
      regenerate: 'Encourage Me Again',
      errorTitle: 'Could not load AI',
      errorGeneric: 'Something went wrong. Please try again.',
    },
    reportGenerator: {
      title: 'Report Generator',
      startDate: 'Start Date',
      endDate: 'End Date',
      last7Days: 'Last 7 Days',
      thisMonth: 'This Month',
      generate: 'Generate',
    },
    goal: {
      title: 'Practice Goal',
      setGoal: 'Set Goal',
      editGoal: 'Edit',
      clearGoal: 'Clear',
      noGoal: 'No practice goal set',
      startDate: 'Start Date',
      endDate: 'End Date',
      targetHours: 'Target Hours (e.g. 20)',
      met: 'Goal met!',
      missed: 'Goal missed',
      startsIn: 'Starts in {days} days',
      daysLeft: '{days} days left',
      needPerDay: 'Need {amount}/day',
      errorDates: 'Please enter a start and end date',
      errorDateOrder: 'End date must be after start date',
      errorHours: 'Target hours must be greater than 0',
    },
    notes: {
      tabLabel: 'Notes',
      subpageByDate: 'By Date',
      subpageByItem: 'By Item',
      addButton: '+ Add note',
      emptyByDate: 'No notes yet. Tap + to add one.',
      emptyByItem: 'No notes',
      createTitle: 'New note',
      editTitle: 'Edit note',
      itemLabel: 'Practice item',
      dateLabel: 'Date',
      bodyLabel: 'Note',
      bodyPlaceholder: 'Write something...',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      itemDeleted: '(deleted)',
      todayLabel: 'Today',
      yesterdayLabel: 'Yesterday',
      noActiveItems: 'No practice items yet. Add one on the Practice tab first.',
      showTrash: 'Show Trash ({count})',
      hideTrash: 'Hide Trash',
      confirmPermanentDelete: 'This will permanently delete this note. This cannot be undone. Continue?',
      emptyTrash: 'Trash is empty.',
    },
  },
  zh: {
    appName: 'Drummate',
    practice: '练习',
    report: '报告',
    metronome: '节拍器',
    addItem: '添加练习项目',
    duplicateItem: '已存在同名的练习项目。',
    enterName: '输入练习项目名称',
    newItemPlaceholder: '新练习项目...',
    add: '添加',
    cancel: '取消',
    edit: '编辑',
    done: '完成',
    archive: '归档',
    unarchive: '取消归档',
    showArchived: '显示已归档',
    hideArchived: '隐藏已归档',
    showTrash: '显示回收站',
    hideTrash: '隐藏回收站',
    restore: '恢复',
    permanentDelete: '永久删除',
    confirmPermanentDelete: '这将永久删除此项目及其所有练习记录。此操作无法撤销。是否继续？',
    daysLeft: '剩余{days}天',
    delete: '删除',
    merge: '合并',
    mergePickerTitle: '合并到…',
    mergeSearchPlaceholder: '搜索项目',
    mergeArchivedTag: '（已归档）',
    mergeEmptyState: '没有其他项目可以合并。',
    mergeConfirmTitle: '确认合并',
    mergeConfirmBody: '将"{source}"合并到"{target}"？"{source}"的所有练习记录将归属到"{target}"。"{source}"将被删除。',
    mergeConfirmAction: '合并',
    mergeNoOtherItems: '没有其他项目',
    start: '开始',
    stop: '停止',
    today: '今天',
    yesterday: '昨天',
    totalPracticeTime: '总练习时间',
    minutes: '分钟',
    hours: '小时',
    timeUnit: '时间单位',
    noPracticeRecorded: '未记录练习',
    noPracticeItems: '未配置练习项目。前往练习页面添加！',
    selectCategory: '选择分类',
    noFundamentalsYet: '还没有基本功项目',
    noSongsYet: '还没有歌曲',
    addFirstItem: '添加你的第一个练习项目',
    generateReport: '生成报告',
    dailyReport: '每日报告',
    copyToClipboard: '复制到剪贴板',
    copied: '已复制！',
    close: '关闭',
    editTime: '编辑时间',
    addTime: '添加时间',
    addManualTime: '添加练习时间',
    durationMinutes: '时长（分钟）',
    save: '保存',
    deleteTime: '删除全部时间',
    confirmDeleteTime: '删除该项目在这一天的所有练习时间？',
    selectItem: '选择项目',
    noItemsToAdd: '所有项目在这一天都已有记录',
    archived: '已归档',
    categories: {
      fundamentals: '基本功',
      songs: '歌曲',
      archived: '已归档',
      fundamentalsShort: '基',
      songsShort: '歌',
    },
    date: '日期',
    total: '总计',
    tapTempo: '敲击节拍',
    accentBeat1: '强调第一拍',
    bpm: 'BPM',
    sequencer: '复杂节奏',
    sequencerEditSlot: '编辑节拍',
    sequencerTapToAdd: '点击添加',
    sequencerEmpty: '点击下方的节奏类型开始构建',
    sequencerInsertBefore: '之前',
    sequencerInsertAfter: '之后',
    rest: '休止',
    soundTypes: {
      click: '咔嗒',
      woodBlock: '木块',
      hiHat: '踩镲',
      rimshot: '边击',
      beep: '蜂鸣',
    },
    tempoNames: {
      grave: '极慢板',
      largo: '广板',
      larghetto: '小广板',
      adagio: '柔板',
      andante: '行板',
      moderato: '中板',
      allegro: '快板',
      vivace: '活泼的快板',
      presto: '急板',
      prestissimo: '最急板',
    },
    auth: {
      signIn: '登录',
      signUp: '注册',
      signOut: '退出',
      email: '邮箱',
      password: '密码',
      name: '显示名称',
      noAccount: '没有账号？',
      hasAccount: '已有账号？',
      syncing: '同步中...',
      sessionExpired: '会话已过期，请重新登录。',
    },
    settings: '设置',
    language: '语言',
    handsFree: {
      title: '免提模式',
      description: '说 "Drummate" 来激活',
      detected: '正在听...',
      listening: '正在聆听指令...',
      commandError: '没有识别到指令',
      commandConfirm: '指令已接收',
      micPermission: '需要麦克风权限',
      loading: '正在加载语音模型...',
      error: '语音检测错误',
      unsupportedBrowser: '免提模式仅支持 Chrome 浏览器。',
    },
    reportSubpages: {
      daily: '每日',
      weekly: '每周',
      monthly: '每月',
      yearly: '每年',
      stats: '统计',
    },
    stats: {
      overview: '概览',
      streaks: '连续记录',
      records: '最佳记录',
      totalPracticeTime: '总练习时间',
      totalPracticeDays: '总练习天数',
      totalSessions: '总练习次数',
      avgDailyTime: '日均练习时间',
      currentStreak: '当前连续天数',
      longestStreak: '最长连续天数',
      longestDayTime: '单日最高练习',
      mostPracticedItem: '练习最多的项目',
      bestMonth: '最佳月份',
      days: '天',
    },
    analytics: {
      totalThisWeek: '本周总计',
      totalThisMonth: '本月总计',
      totalThisYear: '本年总计',
      weekOf: '本周',
      noDataThisWeek: '本周无练习记录',
      noDataThisMonth: '本月无练习记录',
      noDataThisYear: '本年无练习记录',
      weeklyTrend: '每周趋势',
      monthlyTrend: '每月趋势',
      practiceDays: '练习天数',
      weekdays: {
        mon: '一',
        tue: '二',
        wed: '三',
        thu: '四',
        fri: '五',
        sat: '六',
        sun: '日',
      },
      months: {
        jan: '1月', feb: '2月', mar: '3月', apr: '4月',
        may: '5月', jun: '6月', jul: '7月', aug: '8月',
        sep: '9月', oct: '10月', nov: '11月', dec: '12月',
      },
    },
    naturalVoice: {
      title: '自然语音（AI）',
      description: '使用AI自然语音替代系统语音',
      size: '一次性下载：约86 MB',
      downloading: '正在下载语音模型...',
      ready: '已就绪',
      error: '语音模型加载失败',
      requires: '请先启用AI教练或免提模式',
      unsupportedLang: '暂不支持中文',
    },
    aiCoach: {
      title: 'AI教练',
      description: '基于你的练习数据获取个性化鼓励',
    },
    llmCoach: {
      buttonLabel: 'AI教练',
      modalTitle: 'Drummate说...',
      downloadTitle: '认识你的AI教练',
      downloadBody: '基于你的练习数据，使用本地AI模型生成个性化鼓励。',
      downloadSize: '一次性下载：约350 MB',
      downloadPrivacy: '所有运算在你的设备上完成，不会发送任何数据。',
      downloadButton: '下载AI模型',
      downloadOnce: '仅需下载一次',
      downloading: '正在下载AI模型...',
      loading: '正在加载AI模型...',
      generating: '思考中...',
      regenerate: '再来一次鼓励',
      errorTitle: '无法加载AI',
      errorGeneric: '出现了一些问题，请重试。',
    },
    reportGenerator: {
      title: '报告生成器',
      startDate: '开始日期',
      endDate: '结束日期',
      last7Days: '最近7天',
      thisMonth: '本月',
      generate: '生成',
    },
    goal: {
      title: '练习目标',
      setGoal: '设置目标',
      editGoal: '编辑',
      clearGoal: '清除',
      noGoal: '未设置练习目标',
      startDate: '开始日期',
      endDate: '结束日期',
      targetHours: '目标小时（例如 20）',
      met: '目标达成！',
      missed: '目标未达成',
      startsIn: '{days} 天后开始',
      daysLeft: '剩余 {days} 天',
      needPerDay: '每天需要 {amount}',
      errorDates: '请输入开始和结束日期',
      errorDateOrder: '结束日期必须晚于开始日期',
      errorHours: '目标时长必须大于 0',
    },
    notes: {
      tabLabel: '笔记',
      subpageByDate: '按日期',
      subpageByItem: '按项目',
      addButton: '+ 添加笔记',
      emptyByDate: '暂无笔记。点击 + 添加。',
      emptyByItem: '暂无笔记',
      createTitle: '新建笔记',
      editTitle: '编辑笔记',
      itemLabel: '练习项目',
      dateLabel: '日期',
      bodyLabel: '笔记内容',
      bodyPlaceholder: '写点什么……',
      save: '保存',
      cancel: '取消',
      delete: '删除',
      itemDeleted: '(已删除)',
      todayLabel: '今天',
      yesterdayLabel: '昨天',
      noActiveItems: '还没有练习项目。请先在练习页添加一个。',
      showTrash: '显示回收站（{count}）',
      hideTrash: '隐藏回收站',
      confirmPermanentDelete: '这将永久删除此笔记。此操作无法撤销。是否继续？',
      emptyTrash: '回收站为空。',
    },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('drummate_language') || 'en';
  });

  const toggleLanguage = useCallback(() => {
    setLanguage((prev) => {
      const next = prev === 'en' ? 'zh' : 'en';
      localStorage.setItem('drummate_language', next);
      return next;
    });
  }, []);

  const t = useCallback(
    (key, params = {}) => {
      const keys = key.split('.');
      let value = translations[language];
      for (const k of keys) {
        value = value?.[k];
      }
      if (typeof value !== 'string') return key;
      return value.replace(/\{(\w+)\}/g, (_, k) => params[k] ?? `{${k}}`);
    },
    [language],
  );

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
